---
title: "Ecoregion (State Child)"
author: "Rowan R"
date: "2025-12-07"
output: 
  pdf_document:
    extra_dependencies: ["float"]
---

```{r, include=FALSE}
### functions ----
perPlnt_df <- function(df){
  perPlnt <- df %>% 
   # filter(name %in% ecor) %>% 
    group_by(name, plantGenSpp, orig1) %>% 
    summarise(nBees = sum(n),
              nBeeSpp = n_distinct(genSpp), 
              beeSpp = paste0(genSpp, collapse = ", "))
  return(perPlnt) 
}

top10 <- function(df, varName){
  dO <- df %>% 
    arrange(desc({{varName}})) %>% 
    head(n = 10)
  return(dO)
}
```

```{r, include=FALSE, warning=FALSE}

singleEco <- datEcoR %>% 
  filter(name %in% x) 

singleEcoNoMissing <- singleEco %>% 
  st_drop_geometry() %>% 
  filter(!is.na(genSpp)) %>% 
  filter(!is.na(plantGenSpp))

# Only use this data for doing interactions, not species overall etc. since males are removed
singleEcoInt <- singleEcoNoMissing %>% 
  filter(!is.na(genSpp)) %>% 
  filter(!is.na(plantGenSpp)) %>% 
  filter(!sex %in% c("Male", "male")) %>% # removing males for now - not informative for pollen
  group_by(name, genSpp, plantGenSpp, orig1) %>% # might adjust this later - using plant genus
  count()

singleEcoPerPlnt <- perPlnt_df(singleEcoInt) 

```

\newpage
\section {Ecoregion: `r x`}
```{r, include=FALSE, warning=FALSE}
nSppB_e <- n_distinct(singleEco$genSpp)

nSppP_e <- n_distinct(singleEcoNoMissing$plantGenSpp)

sppInts <- singleEcoNoMissing %>% mutate(ints = str_c(genSpp, "-", plantGenSpp))
nInts_e <- n_distinct(sppInts$ints)

```

Total Bee Species: `r nSppB_e`

Total Plant species: `r nSppP_e`

Total Bee-Plant Interactions: `r nInts_e`

```{r, include=FALSE}
tCap <- str_c("Top Plant Species and Genera for Bee Richness in the ", x, " Ecoregion.") 
```

\subsection {Top Plant Genera For Bee Richness}
```{r, echo=FALSE, tab.cap= tCap}
kable(slice_head(singleEcoPerPlnt %>% arrange(desc(nBeeSpp)) %>%ungroup() %>% select(!c(name, beeSpp)), n = 10))
```

\subsection {Most abundant bee species `r x` Ecoregion}

```{r, include=FALSE}
tcap_topb <- paste0("Most Abundant Bee Species of the ", x, " Ecoregion.")
```

```{r, tab.cap= tcap_topb}
kable(slice_head(singleEcoNoMissing %>% 
                   filter(!str_detect(genSpp, "spp\\.")) %>% 
        group_by(genSpp) %>% 
        count() %>%ungroup() %>% 
        arrange(desc(n)), n = 10) )
```

```{r, include=FALSE}
# side by side per county? with county highlighted
ecor2highlight <- stateChao_ecoreg %>% filter(name %in% x) %>% 
  mutate(gap = as.character(round(Estimator - Observed), 0))

# make figure caption
fCap <- paste0("Top: Observed Species in the ", x, " Ecoregion.", " Bottom: Number of Additional Species Expected in the ", x, " Ecoregion.")
```
\subsection {Bee Richness Highlighted for the `r x` Ecoregion}
```{r, fig.height=8, fig.cap= fCap, fig.pos= "H", out.extra= ""}
cowplot::plot_grid(
actualStateRich(stateChao_ecoreg)+
  scale_fill_gradient2(low = "white", 
                       mid = '#f1eef6',
                       high = '#045a8d')+
  geom_sf(data = ecor2highlight, colour = "green", alpha = 0, size = 1)+
    geom_sf_text(data = ecor2highlight, aes(label = Observed), size = 2)+
    labs(x = "", y = "") , 
gapStateRich(stateChao_ecoreg)+
  scale_fill_gradient2(low = "white", 
                       mid = '#ffffcc',
                       high = '#bd0026')+
  geom_sf(data = ecor2highlight, colour = "green", alpha = 0, size = 1)+
  geom_sf_text(data = ecor2highlight, aes(label = gap), size = 2)+
  labs(x = "", y = ""),

nrow = 2
)
```

\subsection {Uncommon Bee Species for the `r x` Ecoregion}
```{r, include=FALSE}
tcap_unc <- paste0("Bees with less than 15 project-wide observations, and less than 10 in the ",  x, " Ecoregion.")
```


```{r, tab.cap= tcap_unc}
kable(singleEcoNoMissing %>% 
  group_by(genSpp) %>% 
  count() %>% ungroup() %>% 
  semi_join(below15_proj, by = "genSpp")
  )
```

