---
title: "County (State Child)"
author: "Rowan R"
date: "2025-12-27"
params: 
  state: ""
output: 
  pdf_document:
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
### functions ----
perPlnt_df_county <- function(df){ # number bees, species per plant 
  perPlnt <- df %>% 
    group_by(county, plantGenSpp, orig1) %>% # replaced name (ecoregion) with county
    summarise(nBees = sum(n),
              nBeeSpp = n_distinct(genSpp), 
              beeSpp = paste0(genSpp, collapse = ", "))
  return(perPlnt) 
}

top10 <- function(df, varName){
  dO <- df %>% 
    arrange(desc({{varName}})) %>% 
    head(n = 10)
  return(dO)
}
```

```{r, include=FALSE, warning=FALSE}

singleCount <- datSt %>% 
  filter(county %in% x) 

singleCountNoMissing <- singleCount %>% st_drop_geometry() %>% 
  filter(!is.na(genSpp)) %>% 
  filter(!is.na(plantGenSpp))

# Only use this data for doing interactions, not species overall etc. since males are removed
singleCountInt <- singleCountNoMissing %>% 
  filter(!is.na(genSpp)) %>% 
  filter(!is.na(plantGenSpp)) %>% 
  filter(!sex %in% c("Male", "male")) %>% # removing males for now - not informative for pollen
  group_by(county, genSpp, plantGenSpp, orig1) %>% # might adjust this later - using plant genus
  count()

singleCountPerPlnt <- perPlnt_df_county(singleCountInt) 

```
\newpage
\section {County: `r x`}
```{r, include=FALSE, warning=FALSE}
nSppB_c <- n_distinct(singleCount$genSpp)

nSppP_c <- n_distinct(singleCountNoMissing$plantGenSpp)

sppInts <- singleCountNoMissing %>% mutate(ints = str_c(genSpp, "-", plantGenSpp))
nInts_c <- n_distinct(sppInts$ints)

```

Total Bee Species: `r nSppB_c`

Total Plant species: `r nSppP_c`

Total Bee-Plant Interactions: `r nInts_c`

```{r, include=FALSE}
tCap <- str_c("Top plant species/genera for bee richness in ", x, " County.")
```

\subsection {Top Plant Genera For Bee Richness}
```{r, echo=FALSE }
tpgen_cty <- slice_head(singleCountPerPlnt %>% arrange(desc(nBeeSpp)) %>%ungroup() %>% select(!c(county, beeSpp)) %>% 
                   rename(`Plant Species` = plantGenSpp, 
                          Origin = orig1,
                          `Number Bee Visits Observed` = nBees,
                          `Bee Species` = nBeeSpp), n = 10)
```

```{r, fig.cap = tCap}
ggplot(tpgen_cty %>% rename(`Bee Species Observed` = `Bee Species`) %>% pivot_longer(cols = contains("Bee"), names_to = "Number", values_to = "val"), aes(x = `Plant Species`, y = `val`, fill = Origin))+
  geom_col()+
  facet_wrap(~Number, scales = "free_x")+
  coord_flip()+
  scale_fill_brewer(palette = "Paired")+
  geom_text(aes(label = `val`), position = position_stack(vjust = 0.5))+
  theme(axis.text.y = element_text(face = "italic"))+ 
  labs(y = "Number")

```


```{r}
# side by side per county? with county highlighted
county2highlight <- stateChao %>% filter(altName %in% x) %>% 
  mutate(gap = as.character(round(Estimator - Observed), 0))

# creating fig caption
fCap <- paste0("Species detected in ", x, " County highlighted relative to nearby counties. Bee record locations are shown as black dots. The yellow text shows the number of species detected within the county.")

```
\newpage
```{r, include = FALSE} 
countQuad <- st_centroid(stateChao) %>% st_join(quadrants, st_within) %>% print(n = 40) %>% 
  select(unitID, instName, altName, quad) %>% st_drop_geometry()

stateChao <- stateChao %>% left_join(countQuad)
whichQuad <- county2highlight %>% left_join(countQuad) %>% pull(quad)
countySubset <- stateChao %>% left_join(countQuad) %>% 
  filter(quad %in% whichQuad)

# ggplot(stateChao)+
#   geom_sf(data = quadrants)+
#   geom_sf(alpha = 0.1)
```

```{r, fig.height=7, fig.width = 7, fig.cap=fCap}
countySppPlot <- actualStateRich(countySubset)+
  scale_fill_gradient2(low = "white",
                       mid = '#f1eef6',
                       high = '#045a8d')+
  geom_sf(data = county2highlight, colour = "green", alpha = 0, size = 1)+
    labs(x = "", y = "", title = str_c(whichQuad, " Quarter of ", stateName))+
  geom_sf(data = datSt %>% filter(county %in% x), size = 0.75)+
  geom_sf_text(data = county2highlight, aes(label = Observed), size = 4, color = "yellow")

countySppPlot
# ggplot(stateCen) +  # Tests whether quadrant system was working
#   geom_sf(data = boundState)+
#   geom_sf()+
#   # geom_sf(data = se)+
#   #   geom_sf(data = nw)
#   geom_sf(data = ne)+
#   geom_sf(data = sw)


# cowplot::plot_grid( # old version with dual maps
# actualStateRich(stateChao)+
#   scale_fill_gradient2(low = "white", 
#                        mid = '#f1eef6',
#                        high = '#045a8d')+
#   geom_sf(data = county2highlight, colour = "green", alpha = 0, size = 1)+
#     geom_sf_text(data = county2highlight, aes(label = Observed), size = 2)+
#     labs(x = "", y = "") , 
# gapStateRich(stateChao)+
#   scale_fill_gradient2(low = "white", 
#                        mid = '#ffffcc',
#                        high = '#bd0026')+
#   geom_sf(data = county2highlight, colour = "green", alpha = 0, size = 1)+
#   geom_sf_text(data = county2highlight, aes(label = gap), size = 2)+
#   labs(x = "", y = ""),
# 
# nrow = 2
# )
```